// Generated by scripts/generate-featured-community-games.mjs. Do not edit by hand.
export const communityAllowlist = Object.freeze([
  {
    "packageID": "authored.51000000-0000-4000-8000-000000000001",
    "canonicalDefinitionDigest": "d87cdc8bdea9224eea926c0350b11b8c454f083231ad158227571dae88e85169"
  },
  {
    "packageID": "authored.51000000-0000-4000-8000-000000000002",
    "canonicalDefinitionDigest": "b942ae619851095d3ceabe49cfad9cd518f7bd2267a3947ed1b224e893760d29"
  },
  {
    "packageID": "authored.51000000-0000-4000-8000-000000000003",
    "canonicalDefinitionDigest": "be2e18e671d0895422d77aa156fee57619b285b1c773642a265fbbb3c06d75d9"
  },
  {
    "packageID": "authored.51000000-0000-4000-8000-000000000004",
    "canonicalDefinitionDigest": "7fd642d21f167c538356cbb65b81262fd24f89d08e9fa6fd00c87ee0f51f327d"
  },
  {
    "packageID": "authored.51000000-0000-4000-8000-000000000005",
    "canonicalDefinitionDigest": "754304d4c29b2663f35021d5fe2085b69c53c4ecb7886dff9d2c22cbcff6a215"
  }
]);
